### ISSUE TITLE
`Stream::flatten_unordered` would be nice

### ISSUE THREAD

**Issue by cramertj** [rust-lang/futures-rs#1781]

**Comment by cramertj** [comment]
Triage: I've seen a number of manual impls of this using `stream::select_all` and `select!`.

**Comment by luser** [comment]
Would this be equivalent to async-std's [`Stream::merge`](https://docs.rs/async-std/1.5.0/async_std/stream/trait.Stream.html#method.merge)?

**Comment by cramertj** [comment]
No-- this would flatten a stream of streams, rather than just combining two streams.

**Comment by luser** [comment]
OK that makes sense but conceptually this is "take a stream of streams and flatten them into a stream that produces items from any of those streams as they become available", right? If so that's effectively what I was asking for [in this async-std issue](https://github.com/async-rs/async-std/issues/693).

**Comment by cramertj** [comment]
Yes, that's what I'm describing.
