### ISSUE TITLE
Consider making `oneshot::Receiver` `Clone`able

### ISSUE THREAD

**Issue by expenses** [rust-lang/futures-rs#1971]
One potential use for `oneshot`s is to send exit signals to kill other futures. However, `oneshot::Receiver`s are not currently `Clone`, despite using an interval `Arc`. When this change is made, the following behaviour occurs:

```rust
let (tx, rx) = oneshot::channel::<u32>();


let future = thread::spawn(|| {
    futures::executor::block_on(
        futures::future::join5(
            rx.clone(),
            rx.clone(),
            rx.clone(),
            rx.clone(),
            rx
        )
    )
});

tx.send(42).unwrap();

assert_eq!(
    future.join().unwrap(),
    (Ok(42), Err(oneshot::Canceled), Err(oneshot::Canceled), Err(oneshot::Canceled), Err(oneshot::Canceled))
);
```

This is actually acceptable behaviour for the purpose of an exit signal, because all you really care about is the future resolving - you'd just `map` the result to an empty tuple (`()`).

**Comment by Pauan** [comment]
That would require the `Sender` to clone the value, which isn't always desirable (or possible). So this functionality should be put onto a new type.

**Comment by expenses** [comment]
@Pauan yeah, that's possibly the best option here

**Comment by Matthias247** [comment]
It's not as easy as cloning the `Receiver`. This is also requires a `T: Clone` bound on the type, which then means it can not be used anymore for non-cloneable values.  And only doing `impl<T: Clone> for Receiver<T>` also doesn't work - because you need different handling in the implementation - cloning the value instead of moving it out of the shared state. That does not work without specialization.

In the current state of Rust you need to write a separate channel type for this. I added such a `OneshotBroadcastChannel` to futures-intrusive. But for the use-case mentioned I would actually recommend an async `ManualResetEvent`.

**Comment by cramertj** [comment]
I don't think this is possible for the current types to handle nicely. If you want this behavior today, you can pass the receiver to the `.shared()` combinator.
