### ISSUE TITLE
Inconsistant naming between future & stream select & join

### ISSUE THREAD

**Issue by jean-airoldie** [rust-lang/futures-rs#1996]
Currently `Future::select`, `Future::select_all` and the `select!` macro all follow the general logic of executing all futures and return with first future to finish.

Intuitively I assumed that `Stream::select` and `Stream::select_all` would be consistent and execute all stream until one stream is terminated then return. However its not the case since they both instead execute until all streams are completed, which is more consistent with the behavior of `Future::join` and `Future::join_all` that execute until all futures are completed.

I think that the current `Stream::select` and `Stream::select_all` should probably named `Stream::join` and `Stream::join_all`, to prevent potential confusion (which occurred in my case). Then I guess that what I get for not fully reading the documentation.

**Comment by YujinGaya** [comment]
I agree that `select` and `select_all` functions of `Stream` can be confusing due to the inconsistency with identically-named functions of `Future`.

But `join` and `join_all` are misleading as some can expect `select_all(streams: Vec<Stream<I>>) -> Stream<Vec<I>>`: wait for every streams to produce at least one item, and return them as a list.

I think `merge` is a good option for the current implementation of `select` and `select_all` of `Stream` because its behavior is different from both `select` and `join`.

**Comment by YujinGaya** [comment]
Possible source of the naming: #239

**Comment by YujinGaya** [comment]
Possible duplication: #760

**Comment by jean-airoldie** [comment]
Yeah its clearly a duplicate, I'll go ahead and close this. Seems like its unlikely to change.
