### ISSUE TITLE
Add bounds to combinators

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/futures-rs#2114]
I suggest adding `Future` and `Stream` bounds to combinators wherever appropriate based on this argument: https://github.com/rust-lang/api-guidelines/issues/217

Acording to [recent reddit post](https://www.reddit.com/r/rust/comments/fubeek/rust_has_to_rework_its_error_reporting/) type errors around `futures` are common (I share the same experience with `0.1`, didn't check `0.3`)

At least until someone comes up with a magical solution for those type errors (which would be awesome because we could safely drop types from function signatures too).

**Comment by taiki-e** [comment]
Note that [adding trait bounds is a breaking change](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#major-change-tightening-bounds).

**Comment by Kixunil** [comment]
Yes, and I think it's worth it. Futures is still not 1.0.

**Comment by taiki-e** [comment]
One of the issues of doing this is the handling of complex bounds.
For example, `try_skip_while` has the following bounds: 
https://github.com/rust-lang/futures-rs/blob/1fa794a593106ac7de3d5bfae09acc5959e0c485/futures-util/src/stream/try_stream/try_skip_while.rs#L41-L43

This bounds is needed for `try_skip_while` to work as a stream, but is it really preferable to always write it (even code that doesn't require `try_skip_while` to be stream)? For example, `try_skip_while` implements `Sink` if the underlying type is `Sink`. If you are trying to use `try_skip_while` as a `Sink`, the suggestions in this issue will make bounds complex but not help you.

The above example may be a bit extreme, but in the end, the actual issue is a diagnostics bug.

**Comment by taiki-e** [comment]
Closing this in favor of upstream discussion. We can revisit this if https://github.com/rust-lang/api-guidelines/issues/217 is accepted.

**Comment by Kixunil** [comment]
You bring a good point and I think in this specific case my point still holds. `TrySkipWhile` is useless without `Stream` as `Sink` impl is essentially no-op.

However one could imagine a type that does something useful for both stream and sink (e.g buffering) in such case I would suggest not bounding the struct but still have two constructors - one for sink, one for stream. So thanks for reminding about this scenario.

**Comment by Kixunil** [comment]
I expanded on the idea in the related issue, hope it's more clear now.
