### ISSUE TITLE
Replace pin-project with pin-project-lite

### ISSUE THREAD

**Issue by stjepang** [rust-lang/futures-rs#2170]
Almost any program doing async I/O uses `futures-utils`, which pulls in `syn` and `quote` dependencies, causing compilation times to be much higher than is needed.

We should consider replacing `pin-project` with `pin-project-line`, which is not using proc macros.

cc @taiki-e

**Comment by taiki-e** [comment]
1. The first step is to merge #2176.
#2176 removes some uses of features that pin-project-lite doesn't support and switches the code to a style compatible with pin-project-lite.

2. After the #2176 is merged, look at the code passing any argument to `#[pin_project]`. These features are not supported in pin-project-lite, so consider whether we can add it to pin-project-lite or write equivalent code without that feature and `unsafe`.

**Comment by stjepang** [comment]
Looks like the first step is done :)

**Comment by taiki-e** [comment]
Yeah. Also, I filed https://github.com/taiki-e/pin-project-lite/pull/25 to start evaluating the second step.

**Comment by taiki-e** [comment]
https://github.com/taiki-e/pin-project-lite/pull/28 adds enum support to pin-project-lite. I'm wondering what syntax is preferable, so I would appreciate any feedback.

**Comment by taiki-e** [comment]
I've released pin-project-lite 0.2 with support for enum. We can probably start this partially.

**Comment by taiki-e** [comment]
This issue seems mentioned in some projects, which already depend on proc-macros. 
For your reference, I'll leave a note:

- **My recommendation as an author of both crates is to use pin-project whenever possible.**
  I think pin-project-lite is a reasonable option only if reducing compile time is really important, and pin-project is the only proc-macro-related dependency.

- As mentioned in pin-project-lite's readme, **if you already have proc-macro-related dependencies in your crate's dependency graph, adding pin-project to a dependency has little impact on compile time.**
  I have previously investigated how little the effect is actually. See https://github.com/tokio-rs/tokio/pull/1588#issuecomment-533917726 for that.

- pin-project-lite is very lightweight, and compile-time does not change whether both pin-project and pin-project-lite are included in the dependency or only pin-project is included in the dependency.

- [The error messages emitted by the current pin-project-lite are very poor](https://github.com/taiki-e/pin-project-lite/issues/36) and may require some knowledge of macro or pin API to determine if it is a macro limitation or a legitimate error.
 In fact, **tokio and async-std had unsoundness that seemed to be due to a misunderstanding of this**: https://github.com/tokio-rs/tokio/pull/2612, https://github.com/async-rs/async-std/pull/903
  (They did unsafe pin-projections for something that the pin-project-lite didn't seem support, but the error is correct and manual pin-projections were unsound)
  pin-project has no limitation like pin-project-lite and can emit decent errors in most cases.
