### ISSUE TITLE
Stream iterator BoxStream SendError

### ISSUE THREAD

**Issue by cryptoquick** [rust-lang/futures-rs#2313]
Hi, I'm trying to return a Sink in a BoxStream, but it works only one time, and throws a SendError the next time send is called, even though there are still additional items left in the stream iterator.

See this code:

https://github.com/FuzzrNet/Fuzzr/blob/d992287e3866a19d69a06fcbb862433a566721b7/src/data/thumbnails.rs

And this issue:

https://github.com/jerry73204/par-stream/issues/1

What causes this error, and what can I do to prevent it?

Also, is this the appropriate repository, or should I post this to async-std?

**Comment by taiki-e** [comment]
> throws a SendError the next time send is called

What is the content of the error?

**Comment by taiki-e** [comment]
> > throws a SendError the next time send is called
> 
> What is the content of the error?

Oh, I'm sorry, I thought you are using futures's channel. async-channel/async-std::channel's SendError is only returned when the receiver closed. So the problem is that `output_rx` is closed when `output_tx.send` called.

Perhaps,`Recipe::stream` needs to return a stream that even if `output_rx` returns `None` returns `Pending` instead of `None`, until `output_rx` receives the same number of futures as `self.path.len`.

**Comment by cryptoquick** [comment]
Thanks for lending me your advice. I was able to solve it in my own way, in case you were curious:
https://github.com/FuzzrNet/Fuzzr/pull/92

I'm honestly not sure where my logic was wrong earlier, but I think it might've been something regarding my application state, not an actual issue with an upstream library. Thank you for your time!
