### ISSUE TITLE
thread 'main' panicked at 'cannot execute `LocalPool` executor from within another executor: EnterError'

### ISSUE THREAD

**Issue by abdelmonem17** [rust-lang/futures-rs#2386]
when I use block_on ,I get this panic and after investigate I found that is because of recursive block_on , so is there is an workaround for that ?
Thank you for advance.

**Comment by seanmonstar** [comment]
Can you `.await` the second future instead of calling `block_on` again?

**Comment by abdelmonem17** [comment]
@seanmonstar if I have an option to await so why I will use block_on ?
I have to use block_on so is there is a way to use block_on ?

**Comment by seanmonstar** [comment]
Not easily at all. 

The panic is there to catch you from a very likely deadlock. That's because if the second block_on isn't ready immediately, it block (put the thread to sleep) until it's ready, but since the thread is asleep, the local pool will never be able to poll again and wake it up.

**Comment by abdelmonem17** [comment]
thank you for help.
regarding to poll next and wake up and executors how can I understand those all ,could you recommend tutorial?

**Comment by seanmonstar** [comment]
This [page in the Tokio tutorial](https://tokio.rs/tokio/tutorial/async) goes into details about `Future`, wakers, executors, etc. If you're newer to async Rust in general, it may help to start reading that tutorial from the beginning, so you have more context, instead of diving into the deep end immediately.
