### ISSUE TITLE
`SendAll` doesn't flush on encountering `Err` from `TryStream`

### ISSUE THREAD

**Issue by ktff** [rust-lang/futures-rs#2402]
The implementation of `fn poll` in `Future` implementation for `SendAll` propagates `Err` case without flushing `Sink`. I think it can be expected from the implementation to flush the sink even in that case that is when the `Stream` errors. 

https://github.com/rust-lang/futures-rs/blob/c77cd3c9ba19b65db3d1931d2087032752fe9c7d/futures-util/src/sink/send_all.rs#L84

**Comment by taiki-e** [comment]
I don't have a strong opinion on this, but I'm okay with accepting a patch to attempt flush when encountering Err on try_poll_next.

Also, `forward` probably has the same problem.

**Comment by Nemo157** [comment]
What would happen if `flush` then also returned an error?

**Comment by taiki-e** [comment]
I was thinking of ignoring the results from the flush (it could also be pending), but that might not actually be a good idea.

**Comment by Nemo157** [comment]
Yeah, it seems like ignoring an error (or `Pending`) sets up a situation where the items up to the error might still not be flushed, and you have no way to know whether the `SendAll` had flushed them or not, so you would still need to flush yourself to ensure they are flushed (or capture the error preventing flushing them). Given that it might be better to just document this behaviour, so that users know to flush on error and can consider how they want to handle the possibility of an error there.
