### ISSUE TITLE
Add into_inner/get methods to more types

### ISSUE THREAD

**Issue by canndrew** [rust-lang/futures-rs#633]
I often want to deconstruct combinator futures/streams back into their components or at least be able to access their components. For example, I want to use `my_stream.map(...)` for a while, then remove the `map` and use `my_stream` again. Or I want implement a `Future` extension trait on types like `AndThen` and `Select` but I need to access their components in order to do it.

Is the lack of methods like `into_inner` and `get_inner` on these types an oversight or is this sort of thing intentionally discouraged (or will we be making these types abstract in the future)?

**Comment by carllerche** [comment]
`get_ref` / `get_mut` / `into_inner` should be on all relevant types unless there is a reason for it to not be.

If there is an obvious impl, it is most likely an oversight and PRs appreciated.

**Comment by canndrew** [comment]
Really, we could just expose the internals of a lot of these types. `Select2`, for example, has an obvious implementation. It's basically:

```rust
enum Select2<A, B> {
    Running(A, B),
    Done,
}
```

It's never going to *not* be implemented like this, so there's no risk of painting ourselves into a corner by exposing its implementation details as part of its public API. It's the same story with all the really basic combinators.

**Comment by alexcrichton** [comment]
I'd prefer to avoid exposing any internals for now, but it's true that we can just add accessors where necessary if they're still missing.

**Comment by carllerche** [comment]
👍 to not exposing internals.

**Comment by canndrew** [comment]
The reason I suggested exposing internals is that I tried implementing the `get_ref`/`get_mut`/`into_inner` methods for `AndThen`, and they look like this:

```rust
impl<A, B, F> AndThen<A, B, F>
where
    A: Future,
    B: IntoFuture,
{
    fn get_ref<'a>(&'a self) -> AndThenInnerRef<'a, A, B, F> {
        match self.state {
            Chain::First(ref a, ref c) => AndThenInnerRef::RunningFirst(a, c),
            Chain::Second(ref b) => AndThenInnerRef::RunningSecond(b),
            Chain::Done => AndThenInnerRef::Done,
        }
    }

    fn get_mut<'a>(&'a mut self) -> AndThenInnerMut<'a, A, B, F> {
        match self.state {
            Chain::First(ref mut a, ref mut c) => AndThenInnerMut::RunningFirst(a, c),
            Chain::Second(ref mut b) => AndThenInnerMut::RunningSecond(b),
            Chain::Done => AndThenInnerMut::Done,
        }
    }

    fn into_inner<'a>(self) -> AndThenInner<A, B, F> {
        match self.state {
            Chain::First(a, c) => AndThenInner::RunningFirst(a, c),
            Chain::Second(b) => AndThenInner::RunningSecond(b),
            Chain::Done => AndThenInner::Done,
        }
    }
}

pub enum AndThenInnerRef<'a, A: 'a, B: 'a, F: 'a>
where
    A: Future,
    B: IntoFuture,
{
    RunningFirst(&'a A, &'a F),
    RunningSecond(&'a B::Future),
    Done,
}

pub enum AndThenInnerMut<'a, A: 'a, B: 'a, F: 'a>
where
    A: Future,
    B: IntoFuture,
{
    RunningFirst(&'a mut A, &'a mut F),
    RunningSecond(&'a mut B::Future),
    Done,
}

pub enum AndThenInner<A, B, F>
where
    A: Future,
    B: IntoFuture,
{
    RunningFirst(A, F),
    RunningSecond(B::Future),
    Done,
}
```

It seems unnecessary to add three new types which just mirror the internal implementation of `AndThen`. I don't know what you guys have planned for this library, but is there any conceivable reason why `AndThen` might ever not be implemented as something identical to `AndThenInner` above? Because if the definition will definitely never change, then it's safe to expose. I understand why not exposing internals is almost always the right thing to do, but given how simple and well-defined the semantics of `AndThen` are I'm not sure it's buying anything here.

Any counter-point? Also, would yous accept the above code-snippet in a PR?

**Comment by alexcrichton** [comment]
Ah yes some of the the combinators I avoided adding these methods originally because of this problem, there wasn't a clear "one liner" defintion. I would personally prefer to not maintain all these variants for all the combinators over time. I think the implementations are relatively simple enough that copying them locally shouldn't be too hard if it' sneeded?

**Comment by tdyas** [comment]
An `into_inner()` method on `StreamFuture` would be useful in the case of `select`ing between the future returned by `stream.into_future()` and a `tokio_core::reactor::Timeout`.

When the timeout occurs, I would like to recover the stream from the `StreamFuture` instead of having to find a way to reuse the `StreamFuture` (because the stream is inaccessible). It leads to code like https://github.com/tdyas/tftp-rs/blob/fd0738f6234c617ab83f11950044ada15e8a1959/src/conn.rs#L132-L156. (The project in question is my attempt to learn Rust. Please forgive rookie mistakes in using futures-await, tokio, etc.)

**Comment by alexcrichton** [comment]
Certainly! @tdyas want to send a PR for the accessors?

**Comment by tdyas** [comment]
Will do.

**Comment by jpathy** [comment]
I would like to add that, using mpsc::Receiver wrapped with ForEach, Fold etc. along with select() on another future, i have often needed to close the underlying channel and process the queued items. I have been copying the implementations and adding the required stream accessors. But it would nice to have these implemented upstream.

**Comment by pmarcelll** [comment]
I tried to implement a multithreaded microbenchmark with futures and I was a bit surprised that the Zip and Chain combinators don't provide a way to recover the streams. Zip is tricky, because also returning the buffered element requires extra logic (or as discussed earier, exposing internals), but Chain could just simply return both streams.

**Comment by H2CO3** [comment]
Neat, that definitely sounds like a clever way of avoiding special-casing in users' code.

**Comment by taiki-e** [comment]
Done in #1544 and #2128. If there is a combinator you think we forgot to add accessors, I'd suggest open an issue or PR.
